import json, sys

OUT = sys.argv[1]
doc = json.load(open(OUT, encoding="utf-8"))

doc["performance"] = {
    "measurementWindow": "2026-09-15 13:55Z - 14:45Z live probes; pg_stat_statements since 2026-09-09T05:49:06Z (6d 08h); Lightsail CloudWatch 2026-09-08 - 2026-09-15",
    "host": {
        "instance": "AWS Lightsail csx-prod-1, bundle small_3_0, 2 vCPU burstable / 2 GB RAM",
        "loadAverage1_5_15": [6.15, 7.03, 6.10],
        "vmstatStealPct": [76, 80, 77, 79],
        "vmstatIdlePct": [3, 0, 3, 0],
        "cpuUtilizationPctPinnedAt": 20.0,
        "burstCapacityPct": 0.0,
        "burstExhaustedSince": "2026-09-13T21:00+09:00",
        "memTotalMB": 1906,
        "memAvailableMB": 366,
        "swapUsedMB": 404,
        "pagesSwappedInSinceBoot": 9989094,
        "pagesSwappedOutSinceBoot": 11295783,
        "swapBytesInSinceBoot": 9989094 * 4096,
        "swapBytesOutSinceBoot": 11295783 * 4096,
        "uptimeDays": 3.32,
    },
    "containers": {
        "server": {
            "memLimitMB": 768,
            "memUsedMB": 659.7,
            "memPct": 85.9,
            "goMemLimit": "600MiB",
            "aboveGoMemLimit": True,
            "cpuSecondsUsed": 14111,
            "elapsedSeconds": 15436,
            "cpuPerCore": 0.914,
            "blockIOReadGB": 3.9,
            "blockIOWriteGB": 3.25,
        },
        "db": {
            "memLimitMB": 640,
            "memUsedMB": 392.3,
            "sharedBuffers": "256MB",
            "databaseSizeMB": 1430,
            "blockIOReadTB": 1.04,
            "blockIOWriteGB": 169,
        },
    },
    "findings": [
        {
            "id": "P0-1",
            "severity": "P0",
            "title": "Package detail pages return 503 'database busy' for the large majority of requests",
            "evidence": {
                "probe": "6 sequential GETs per path, 2026-09-15T14:30Z",
                "results": {
                    "/npm/axios": {"http200": 0, "http503": 6},
                    "/npm/react": {"http200": 0, "http503": 6},
                    "/golang/github.com/google/uuid": {"http200": 1, "http503": 5, "successTtfbSeconds": 10.13},
                    "/pypi/sqlalchemy": {"http200": 1, "http503": 5},
                },
                "sustainedProbe": {
                    "path": "/golang/github.com/google/uuid",
                    "attempts": 25,
                    "http200": 0,
                    "http503": 25,
                    "windowSeconds": 35,
                },
                "responseBody": "{\"error\":\"database busy\"}",
                "aggregateFailureRate": "22/24 = 91.7% over the four-path probe",
            },
            "mechanism": "Three stacked admission layers each with a ~250ms budget: withPackageLoadSlot (4 slots, 250ms), the interactive pool (CSX_DB_READ_CONNS=2, CSX_DB_READ_WAIT=250ms), and snapshotLoadRetryDefer (15s post-failure blackout). Under builder CPU contention the underlying snapshot read takes 10-36s, so no request can hold a slot long enough to fill the 30-minute package cache, and the cache can only be filled by a request that succeeds.",
            "classification": "server+DB, not browser, not payload, not cold-start",
        },
        {
            "id": "P0-2",
            "severity": "P0",
            "title": "Production host has exhausted Lightsail CPU burst capacity and is clamped to 20% baseline",
            "evidence": {
                "burstCapacityPercentage": "0.00 avg / 0.00 max for the 2026-09-13T21:00 through 2026-09-15T21:00 window; <=0.64 for most of 2026-09-08 through 2026-09-13",
                "cpuUtilization": "exactly 20.00 avg with 20.03-20.14 max for days at a time - a throttle ceiling, not a workload shape",
                "vmstatSteal": "76-80%",
                "loadAverage": "6.1-7.0 on 2 vCPU",
                "onlyRecoveryWindow": "2026-09-12T15:00 through 2026-09-13T15:00, burst recovered to 56.41% and CPU rose to 32-51% avg, then burned back to zero",
            },
            "effectiveComputeCores": 0.4,
            "classification": "host / infrastructure",
        },
        {
            "id": "P0-3",
            "severity": "P0",
            "title": "Compatibility builder consumes ~0.9 vCPU continuously at a 78% duty cycle, starving every request path",
            "evidence": {
                "fullPassWallClock": "2026-09-15T10:44:03 to 12:56:25 = 2h12m22s",
                "fullPassBreakdown": {
                    "targets": 21678,
                    "packages": 3135,
                    "clusters": 234837,
                    "clusterReadSeconds": 86.1,
                    "clusterCalculateSeconds": 692.8,
                    "clusterWriteSeconds": 1989.4,
                },
                "dutyCycle": "201 of 257 wall-clock minutes busy between 09:39 and 13:56 = 78%",
                "interval": "CSX_SNAPSHOT_INTERVAL=5m - the gap between passes, not the period",
                "projectsOwnMeasurement": "cmd/csx-server/webstore.go: the snapshot read costs 0.59s with the builder idle and 36.5s while a builder pass runs - 62x, all buffer hits, CPU contention not disk",
            },
            "classification": "aggregation/rebuild work colliding with request paths",
        },
        {
            "id": "P1-4",
            "severity": "P1",
            "title": "Production pool policy is 3x tighter on connections and 12x tighter on wait than the shipped default",
            "evidence": {
                "CSX_DB_READ_CONNS": "2 (DefaultPoolPolicy.InteractiveConns = 6)",
                "CSX_DB_READ_WAIT": "250ms (DefaultPoolPolicy.ReadWait = 3s)",
                "CSX_DB_MAX_CONNS": "unset, so 8",
                "poolBusyEventsIn24h": 999,
                "queryTimeoutEventsIn24h": 93,
                "admissionRefusedIn24h": 8,
                "deferredRefusedIn24h": 18,
                "note": "log lines are throttled to one per second per class, so these are lower bounds",
                "healthzPoolBusyIn24h": 58,
                "healthzMaxObservedWaitSeconds": 1.443,
            },
            "classification": "DB pool pressure",
        },
        {
            "id": "P1-5",
            "severity": "P1",
            "title": "Admin farm panel times out; its backlog aggregate is uncached and polled every 60s",
            "evidence": {
                "adminApiFarmQueryTimeoutsIn24h": 76,
                "farmBacklogNowMeanMs": 10409.18,
                "farmBacklogNowMaxMs": 22855.1,
                "farmBacklogNowCalls": 2103,
                "farmAggregateTimeout": "25s",
                "adminPollInterval": "60s (internal/admin/static/admin.js setInterval(load, 60000) x2)",
                "queriesPerFarmRequest": "FarmWorkers, FarmHealthNow, FarmBacklogNow, FarmCompletenessNow, coverage - five sequential uncached aggregates",
                "failureBody": "HTTP 503 with the Korean string for 'could not load the backlog'",
            },
            "classification": "aggregation on an interactive request path",
        },
        {
            "id": "P1-6",
            "severity": "P1",
            "title": "builder_purl_coord SQL function costs 16.5ms per evaluation and is maintained on expression indexes over the two hottest write tables",
            "evidence": {
                "measured10kEvaluationsMs": 165432.1,
                "perCallMs": 16.54,
                "lowerBaseline10kMs": 246.4,
                "lowerPerCallMs": 0.0246,
                "ratio": 672,
                "pgStatStatementsCalls": 10358032,
                "pgStatStatementsTotalSeconds": 65366.6,
                "pctOfOneCoreOverWindow": 11.9,
                "expressionIndexes": [
                    "evidence_agg_builder_coord_idx ON evidence_agg(builder_purl_coord(purl), purl, symbol)",
                    "snapshots_builder_coord_idx ON compatibility_snapshots(builder_purl_coord(purl), purl, symbol)",
                ],
                "writesRequiringEvaluation": {
                    "evidence_agg_inserts": 401229,
                    "evidence_agg_updates": 400961,
                    "compatibility_snapshots_inserts": 2322683,
                },
            },
            "classification": "long query / index maintenance cost",
        },
        {
            "id": "P1-7",
            "severity": "P1",
            "title": "Sequential scans read ~55 billion tuples from tables of 8k-320k rows",
            "evidence": {
                "sample_packages": {"liveRows": 8676, "seqScans": 3783022, "seqTuplesRead": 25052104800},
                "evidence_agg": {"liveRows": 318441, "seqScans": 255307, "seqTuplesRead": 9395035302},
                "samples": {"liveRows": 8345, "seqScans": 2575987, "seqTuplesRead": 7553405879},
                "receipts": {"liveRows": 10965, "seqScans": 1352559, "seqTuplesRead": 6948496704},
                "dependency_edge": {"liveRows": 109686, "seqScans": 123603, "seqTuplesRead": 3360173687},
                "compatibility_snapshots": {"liveRows": 21686, "seqScans": 86780, "seqTuplesRead": 1203005922},
                "packages": {"liveRows": 6330, "seqScans": 188017, "seqTuplesRead": 714003678},
                "indexScanHotspots": {
                    "sample_packages_coord_idx": 35675890,
                    "evidence_agg_target_idx": 270928044,
                },
                "dbContainerBlockReadsTB": 1.04,
            },
            "classification": "N+1 / missing-bound reads",
        },
        {
            "id": "P1-8",
            "severity": "P1",
            "title": "csx-server runs permanently above GOMEMLIMIT, so the Go collector is in continuous back-to-back GC",
            "evidence": {
                "rssMB": 659.7,
                "goMemLimitMB": 629.1,
                "containerLimitMB": 768,
                "memPctOfLimit": 85.9,
                "goRuntimeBehaviour": "above the soft limit the collector runs continuously, capped by the runtime at 50% of GOMAXPROCS (=2 here, so up to 1 core)",
                "historicalOOMKills": "three on 2026-09-01 at anon-rss 741872kB / 697448kB / 694388kB, documented in deploy/docker-compose.yml",
                "healthcheckFailures": "docker health log shows exit=8 at 14:13:47 and 14:13:59 on 2026-09-15",
            },
            "classification": "resource pressure / GC",
        },
        {
            "id": "P2-9",
            "severity": "P2",
            "title": "HotPackages cache TTL is 60s for a ranking that changes on the builder's multi-hour cadence",
            "evidence": {
                "hotPackagesTTL": "1m",
                "underlyingQuery": "SELECT purl, symbol FROM compatibility_snapshots ORDER BY purl, symbol",
                "calls": 4976,
                "meanMs": 1470.25,
                "maxMs": 32236.4,
                "totalSeconds": 7316.0,
                "rowsReturnedTotal": 103244335,
                "rowsPerCall": 20748,
                "consumer": "internal/web/landing.go renders 12 rows from it",
            },
            "classification": "cache topology",
        },
        {
            "id": "P2-10",
            "severity": "P2",
            "title": "Authoring expansion candidate query takes 3 to 7 minutes per call",
            "evidence": {
                "calls": 192,
                "meanMs": 183436.34,
                "maxMs": 432954.9,
                "totalSeconds": 35219.8,
                "secondVariantCalls": 2103,
                "secondVariantMeanMs": 10409.18,
                "thirdVariantCalls": 1059,
                "thirdVariantMeanMs": 10142.61,
                "combinedSeconds": 67850,
                "source": "internal/serverstore/dependencyclosure_pg.go authoringCoverageCTE - dependency_open CROSS JOIN LATERAL over dependency_edge with four EXISTS probes, two of them against un-indexed MATERIALIZED CTEs",
                "acknowledgedInCode": "ListAuthoringExpansionCandidatesUnhurried comment: 'the ~4 minutes the read needs on production'",
            },
            "classification": "long query",
        },
        {
            "id": "P2-11",
            "severity": "P2",
            "title": "Anonymous analytics writes fail continuously",
            "evidence": {
                "logLine": "csx: anonymous analytics write unavailable (activity undercounted)",
                "observedRate": "roughly one line every 2-15 seconds in the server log",
                "consequence": "the activity figures the admin dashboard and /v1/stats report are undercounts of unknown size",
            },
            "classification": "correctness under load",
        },
    ],
    "latency": {
        "note": "curl --compressed, TTFB vs total, 2026-09-15T14:2xZ. Payload transfer is negligible; the cost is server time-to-first-byte.",
        "samples": [
            {"path": "/compatibility", "status": 200, "ttfbSeconds": 6.98, "totalSeconds": 7.06, "bytes": 7649},
            {"path": "/", "status": 200, "ttfbSeconds": 1.25, "totalSeconds": 1.40, "bytes": 11453},
            {"path": "/dependencies", "status": 200, "ttfbSeconds": 1.09, "totalSeconds": 1.09, "bytes": 8043},
            {"path": "/npm/axios", "status": 503, "ttfbSeconds": 1.23, "totalSeconds": 1.28, "bytes": 4024},
        ],
        "repeatedMedians": {
            "/v1/stats": {"n": 10, "ok": 10, "minS": 1.42, "medianS": 2.22, "p90S": 4.14, "maxS": 7.70},
            "/": {"n": 10, "ok": 10, "minS": 1.92, "medianS": 3.02, "p90S": 4.76, "maxS": 6.23},
            "/compatibility": {"n": 10, "ok": 10, "minS": 3.77, "medianS": 6.17, "p90S": 7.67, "maxS": 9.80},
            "/gaps": {"n": 10, "ok": 10, "minS": 0.85, "medianS": 1.07, "p90S": 1.65, "maxS": 1.92},
            "/dependencies": {"n": 10, "ok": 10, "minS": 0.73, "medianS": 0.92, "p90S": 1.07, "maxS": 1.29},
            "/v1/samples/{id}": {"n": 12, "ok": 3, "http503": 9, "okRangeS": [2.65, 5.50]},
        },
        "documentedExpectation": "internal/serverstore/pool.go: 'ordinary pages take 30-170ms'. Measured medians are 6x to 40x that; package pages do not complete at all.",
    },
    "topQueriesByTotalTime": [
        {"totalSeconds": 95048.0, "calls": 336604, "meanMs": 282.37, "maxMs": 7999.7, "rows": 55431292, "bufferMissPct": 56.2, "queryPrefix": "SELECT id, COALESCE(ecosystem,$2), COALESCE(package_name,$3), ... FROM failure_clusters"},
        {"totalSeconds": 65366.6, "calls": 10358032, "meanMs": 6.31, "maxMs": 5847.8, "rows": 10358032, "bufferMissPct": 38.8, "queryPrefix": "builder_purl_coord body (regexp_match + percent-decode + convert_from)"},
        {"totalSeconds": 41416.0, "calls": 20025622, "meanMs": 2.07, "maxMs": 787.1, "rows": 84580, "bufferMissPct": 9.1, "queryPrefix": "INSERT INTO failure_clusters(...) ON CONFLICT"},
        {"totalSeconds": 35219.8, "calls": 192, "meanMs": 183436.34, "maxMs": 432954.9, "rows": 38400, "bufferMissPct": 41.0, "queryPrefix": "WITH verified_samples AS MATERIALIZED ... (authoring expansion candidates)"},
        {"totalSeconds": 21890.5, "calls": 2103, "meanMs": 10409.18, "maxMs": 22855.1, "rows": 2103, "bufferMissPct": 9.1, "queryPrefix": "WITH verified_samples AS MATERIALIZED ... (farm backlog stocks)"},
        {"totalSeconds": 14692.4, "calls": 2322683, "meanMs": 6.33, "maxMs": 1287.0, "rows": 2322683, "bufferMissPct": 4.7, "queryPrefix": "INSERT INTO compatibility_snapshots(...) ON CONFLICT"},
        {"totalSeconds": 13711.0, "calls": 2494605, "meanMs": 5.50, "maxMs": 36715.4, "rows": 33257188, "bufferMissPct": 25.0, "queryPrefix": "SELECT purl, symbol, symbol_confidence, env_hash, ... FROM evidence_agg"},
        {"totalSeconds": 13092.7, "calls": 7635, "meanMs": 1714.83, "maxMs": 9374.0, "rows": 7635, "bufferMissPct": 1.2, "queryPrefix": "WITH pub AS (... jsonb_array_elements_text over manifests ...)"},
        {"totalSeconds": 10741.0, "calls": 1059, "meanMs": 10142.61, "maxMs": 22814.4, "rows": 1059, "bufferMissPct": 9.2, "queryPrefix": "WITH verified_samples AS MATERIALIZED ... (third variant)"},
        {"totalSeconds": 9743.7, "calls": 430515, "meanMs": 22.63, "maxMs": 4718.3, "rows": 2591272, "bufferMissPct": 27.0, "queryPrefix": "SELECT purl, symbol, snapshot::text FROM compatibility_snapshots WHERE purl = $1"},
        {"totalSeconds": 7316.0, "calls": 4976, "meanMs": 1470.25, "maxMs": 32236.4, "rows": 103244335, "bufferMissPct": 23.5, "queryPrefix": "SELECT purl, symbol FROM compatibility_snapshots ORDER BY purl, symbol"},
        {"totalSeconds": 4727.7, "calls": 624, "meanMs": 7576.49, "maxMs": 27519.9, "rows": 3120000, "bufferMissPct": 73.2, "queryPrefix": "SELECT purl, SUM(observation_count) FROM evidence_agg GROUP BY purl ORDER BY n DESC LIMIT $1"},
        {"totalSeconds": 3190.4, "calls": 150, "meanMs": 21269.28, "maxMs": 101851.7, "rows": 150, "bufferMissPct": 44.9, "queryPrefix": "SELECT (SELECT COUNT(DISTINCT bucket) FROM evidence_dedup ...) (stats rollup)"},
        {"totalSeconds": 2132.2, "calls": 115, "meanMs": 18540.98, "maxMs": 477291.0, "rows": 979883, "bufferMissPct": 0.2, "queryPrefix": "SELECT r.receipt::text, s.manifest::text FROM samples s JOIN receipts r"},
    ],
}

json.dump(doc, open(OUT, "w", encoding="utf-8"), indent=1, ensure_ascii=False)
print("performance section added; findings=" + str(len(doc["performance"]["findings"])))
