// Package samples implements the local half of the public-sample pipeline
// (goal.md §9, plan C13): canonical content-addressed artifacts, leakage
// scanning, sanitized clean-room specs, and the create workflow. Nothing in
// this package ever transmits data; publishing is a separate, explicit step.
package samples

import (
	"archive/tar"
	"bytes"
	"compress/gzip"
	"errors"
	"fmt"
	"io"
	"io/fs"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strings"
	"time"

	"github.com/r2cuerdame/codesamplex/internal/domain"
)

// Artifact limits (goal.md §16.4, plan C13).
const (
	// MaxCompressedBytes caps the canonical tar.gz size.
	MaxCompressedBytes = 256 * 1024
	// MaxFiles caps the number of regular files in a sample.
	MaxFiles = 200
	// maxUnpackedBytes bounds decompression on Unpack (bomb guard).
	maxUnpackedBytes = 8 << 20
	// maxUnpackEntries bounds total tar entries (files + dirs) on Unpack.
	maxUnpackEntries = 2 * MaxFiles
)

// generatedDirNames are directories that appear in a sample tree because
// something RAN there — most often csx itself. `csx sample check` mounts
// the sample dir as the sandbox workspace, so a check leaves .csx-vendor
// behind, and the toolchain leaves deps/, _build/, vendor/, .dart_tool/,
// target/ next to it.
//
// They are skipped, not refused. The documented workflow is check and then
// create, and refusing meant the second command failed on directories the
// first one had written: an error naming a directory the user never made,
// with no hint that deleting it was safe. Every one of these is output that
// the artifact must not carry either way, so skipping reaches the same
// artifact by a route that does not stop the user — and it makes the sample
// ID independent of whether a check was run first, which refusing did not.
//
// Skipping is only correct because it cannot hide anything: Unpack still
// REJECTS these entries, so an artifact that carries one is refused on
// arrival no matter who built it.
var generatedDirNames = map[string]bool{
	"node_modules": true,
	"target":       true,
	"dist":         true,
	// A virtualenv is generated by any Python workflow that resolves
	// dependencies, which is every Python sample. It was a hard error on
	// the reasoning that csx does not create one — true, and beside the
	// point: `python -m venv` does, and the person or agent authoring the
	// sample runs that. Nobody has ever meant to publish one.
	"venv":  true,
	".venv": true,
	// Any depth, because that is where these appear: running a contract in
	// a seed directory leaves src/__pycache__, never a root one. Bytecode
	// is stamped with the interpreter that wrote it — cpython-310 on the
	// publishing machine, in a sample whose environment says python 3.12 —
	// so it is host detail in a document meant to carry none.
	"__pycache__":   true,
	".pytest_cache": true,
	".mypy_cache":   true,
	".ruff_cache":   true,
}

// forbiddenDirNames is what csx never creates and nobody generates by
// working: a .git tree means the user pointed csx at a repository root
// rather than at a sample, and silently publishing a subset of what they
// pointed at would be worse than stopping.
var forbiddenDirNames = map[string]bool{
	".git": true,
}

func forbiddenDir(seg string) bool { return forbiddenDirNames[strings.ToLower(seg)] }

func generatedDir(seg string) bool { return generatedDirNames[strings.ToLower(seg)] }

// generatedRootDirNames are resolve output directories that are only
// generated at the project root. They are matched at the root ONLY: a
// sample may legitimately contain src/vendor/ or lib/deps/, and skipping
// those names at any depth would silently drop honest source to catch a
// mistake that can only happen one level up.
var generatedRootDirNames = map[string]bool{
	"vendor":      true, // composer, and go's vendored module tree
	"deps":        true, // mix
	"_build":      true, // mix
	".dart_tool":  true, // dart pub
	".csx-vendor": true, // this project's own two-phase resolve output
	".bundle":     true, // bundler config written during install
}

func generatedRootDir(slash string) bool {
	if strings.Contains(slash, "/") {
		return false
	}
	return generatedRootDirNames[strings.ToLower(slash)]
}

// forbiddenRootDir reports whether an INCOMING artifact entry names a
// resolve output directory. Unpack keeps rejecting what BuildArtifact now
// skips: a tar that carries one was not built by this code path.
func forbiddenRootDir(slash string) bool { return generatedRootDir(slash) }

// generatedFileNames are test-runner scratch files. They are not secrets —
// the phpunit one holds test names and timings — but they are output, not
// source, and they change the artifact hash, so the same sample published
// twice gets two content addresses for no reason. One reached the network
// before this check existed.
var generatedFileNames = map[string]bool{
	".phpunit.result.cache": true,
	".rspec_status":         true,
	".byebug_history":       true,
	"npm-debug.log":         true,
	"yarn-error.log":        true,
	"erl_crash.dump":        true,
}

// generatedFileExts are compiled outputs. A sample is source plus a
// lockfile; anything already compiled is both redundant and stamped with
// the machine that compiled it.
var generatedFileExts = map[string]bool{
	".pyc": true, ".pyo": true, ".class": true, ".beam": true, ".o": true,
}

func generatedFile(base string) bool {
	lower := strings.ToLower(base)
	return generatedFileNames[lower] || generatedFileExts[path.Ext(lower)]
}

// forbiddenFile reports whether an INCOMING artifact entry names run
// output, for the same reason as forbiddenRootDir.
func forbiddenFile(base string) bool { return generatedFile(base) }

// isEnvFile reports whether base names a dotenv secrets file (.env, .env.local, …).
func isEnvFile(base string) bool {
	lower := strings.ToLower(base)
	return lower == ".env" || strings.HasPrefix(lower, ".env.")
}

// BuildArtifact renders dir as the canonical sample artifact: files sorted
// by slash-path, tar mode 0644, uid/gid 0, mtime Unix epoch 0, USTAR only
// (no PAX or user headers), gzip with zero MTime and no name. The returned
// sampleID is domain.SHA256Hex over the tar.gz bytes, so identical trees
// always produce identical IDs regardless of file timestamps.
func BuildArtifact(dir string) (tgz []byte, sampleID string, err error) {
	paths, err := collectFiles(dir)
	if err != nil {
		return nil, "", err
	}
	if len(paths) == 0 {
		return nil, "", errors.New("samples: empty sample directory")
	}
	if len(paths) > MaxFiles {
		return nil, "", fmt.Errorf("samples: %d files exceeds the %d-file limit", len(paths), MaxFiles)
	}
	sort.Strings(paths)

	var buf bytes.Buffer
	gz := gzip.NewWriter(&buf) // Header: zero MTime, empty Name — canonical.
	tw := tar.NewWriter(gz)
	var unpacked int64
	for _, p := range paths {
		// Everything Unpack will refuse has to be refused HERE, while the
		// author can still act on it.
		//
		// Only the compressed size was checked at creation, and Unpack
		// enforces three more rules: a per-entry and total unpacked cap, a
		// name safety rule, and USTAR encodability. So `csx sample create`
		// happily minted samples that preview, verify and publish then
		// refused forever, with no way to make progress: a 9MB fixture
		// compresses to 32KB and passes the only gate there was, and a
		// file named with a colon (legal on Linux and macOS, and what an
		// ISO timestamp looks like) passed too.
		if err := buildableEntryName(p); err != nil {
			return nil, "", err
		}
		content, rerr := os.ReadFile(filepath.Join(dir, filepath.FromSlash(p)))
		if rerr != nil {
			return nil, "", fmt.Errorf("samples: read %s: %w", p, rerr)
		}
		if bytes.IndexByte(content, 0) >= 0 {
			return nil, "", fmt.Errorf("samples: binary file not allowed: %s", p)
		}
		if int64(len(content)) > maxUnpackedBytes {
			return nil, "", fmt.Errorf(
				"samples: %s is %d bytes; a sample file may be at most %d. "+
					"Trim the fixture or generate it in the contract instead",
				p, len(content), maxUnpackedBytes)
		}
		unpacked += int64(len(content))
		if unpacked > maxUnpackedBytes {
			return nil, "", fmt.Errorf(
				"samples: the sample totals more than %d bytes unpacked. "+
					"A sample is a minimal project; move large fixtures out of it",
				maxUnpackedBytes)
		}
		hdr := &tar.Header{
			Typeflag: tar.TypeReg,
			Name:     p,
			Size:     int64(len(content)),
			Mode:     0o644,
			Uid:      0,
			Gid:      0,
			ModTime:  time.Unix(0, 0),
			Format:   tar.FormatUSTAR,
		}
		if werr := tw.WriteHeader(hdr); werr != nil {
			return nil, "", fmt.Errorf("samples: tar %s: %w", p, werr)
		}
		if _, werr := tw.Write(content); werr != nil {
			return nil, "", fmt.Errorf("samples: tar %s: %w", p, werr)
		}
	}
	if err := tw.Close(); err != nil {
		return nil, "", fmt.Errorf("samples: close tar: %w", err)
	}
	if err := gz.Close(); err != nil {
		return nil, "", fmt.Errorf("samples: close gzip: %w", err)
	}
	if buf.Len() > MaxCompressedBytes {
		return nil, "", fmt.Errorf("samples: artifact is %d bytes, limit is %d", buf.Len(), MaxCompressedBytes)
	}
	tgz = buf.Bytes()
	return tgz, domain.SHA256Hex(tgz), nil
}

// collectFiles walks dir enforcing the pre-build safety rules and returns
// the sorted-later slash-relative paths of every regular file.
func collectFiles(dir string) ([]string, error) {
	var paths []string
	err := filepath.WalkDir(dir, func(p string, d fs.DirEntry, err error) error {
		if err != nil {
			return err
		}
		rel, rerr := filepath.Rel(dir, p)
		if rerr != nil {
			return rerr
		}
		if rel == "." {
			return nil
		}
		slash := filepath.ToSlash(rel)
		if strings.HasPrefix(slash, "..") || path.IsAbs(slash) {
			return fmt.Errorf("samples: path escapes sample dir: %s", slash)
		}
		base := path.Base(slash)
		if d.Type()&fs.ModeSymlink != 0 {
			return fmt.Errorf("samples: symlink not allowed: %s", slash)
		}
		// A repository marker is not always a directory. In a git WORKTREE
		// or a submodule, .git is a small regular FILE holding "gitdir:
		// /path/to/repo/.git/worktrees/x" -- so the guard below, which
		// only looks at directories, let it through, and the packaged
		// sample carried a path from the contributor's machine straight
		// into a published artifact. Worktrees are the ordinary way to
		// work on two things at once, so this is not an exotic setup.
		if !d.IsDir() && forbiddenDir(base) {
			return fmt.Errorf(
				"samples: %s is a repository marker, not sample content — "+
					"this directory is a git worktree or submodule. Copy the "+
					"minimal project somewhere of its own and run this again", slash)
		}
		if d.IsDir() {
			if generatedDir(base) || generatedRootDir(slash) {
				return filepath.SkipDir
			}
			if forbiddenDir(base) {
				// A dead end without a reason is a dead end. This one is a
				// deliberate stop rather than a filter: a .git directory
				// means the sample directory is somebody's actual
				// repository, and packaging one publishes remotes, author
				// identities, commit messages and every file the author was
				// not thinking about. Skipping it silently would publish
				// the rest of that tree, so the answer is to say why and
				// what to do instead.
				return fmt.Errorf(
					"samples: %s/ is a repository, not a sample directory — "+
						"packaging it would publish its remotes, authors and history. "+
						"Copy the minimal project into a directory of its own "+
						"(or remove %s/) and run this again", slash, slash)
			}
			return nil
		}
		if !d.Type().IsRegular() {
			return fmt.Errorf("samples: non-regular file not allowed: %s", slash)
		}
		// A dotenv file is the one thing here that is neither output nor
		// recoverable: skipping it would publish nothing but would also say
		// nothing, and the next command would try again. It stops.
		if isEnvFile(base) {
			return fmt.Errorf("samples: forbidden entry: %s", slash)
		}
		if generatedFile(base) {
			return nil
		}
		paths = append(paths, slash)
		return nil
	})
	if err != nil {
		return nil, err
	}
	return paths, nil
}

// Unpack extracts a sample artifact into destDir with the same safety
// posture as BuildArtifact: clean relative paths only, no traversal or
// absolute names, forbidden entries rejected, compressed and decompressed
// size caps, and no write can land outside destDir.
func Unpack(tgz []byte, destDir string) error {
	if len(tgz) > MaxCompressedBytes {
		return fmt.Errorf("samples: artifact is %d bytes, limit is %d", len(tgz), MaxCompressedBytes)
	}
	gz, err := gzip.NewReader(bytes.NewReader(tgz))
	if err != nil {
		return fmt.Errorf("samples: unpack: %w", err)
	}
	defer gz.Close()

	tr := tar.NewReader(gz)
	var files, entries int
	var total int64
	for {
		hdr, err := tr.Next()
		if errors.Is(err, io.EOF) {
			break
		}
		if err != nil {
			return fmt.Errorf("samples: unpack: %w", err)
		}
		entries++
		if entries > maxUnpackEntries {
			return fmt.Errorf("samples: unpack: more than %d entries", maxUnpackEntries)
		}
		isDir := hdr.Typeflag == tar.TypeDir
		clean, err := safeEntryName(hdr.Name, isDir)
		if err != nil {
			return err
		}
		target := filepath.Join(destDir, filepath.FromSlash(clean))
		if !within(destDir, target) {
			return fmt.Errorf("samples: unpack: entry %q escapes destination", hdr.Name)
		}
		switch hdr.Typeflag {
		case tar.TypeDir:
			if err := os.MkdirAll(target, 0o755); err != nil {
				return fmt.Errorf("samples: unpack: %w", err)
			}
		case tar.TypeReg:
			files++
			if files > MaxFiles {
				return fmt.Errorf("samples: unpack: more than %d files", MaxFiles)
			}
			if hdr.Size < 0 || hdr.Size > maxUnpackedBytes {
				return fmt.Errorf("samples: unpack: entry %s is %d bytes", clean, hdr.Size)
			}
			total += hdr.Size
			if total > maxUnpackedBytes {
				return fmt.Errorf("samples: unpack: exceeds %d-byte unpacked cap", maxUnpackedBytes)
			}
			if err := os.MkdirAll(filepath.Dir(target), 0o755); err != nil {
				return fmt.Errorf("samples: unpack: %w", err)
			}
			f, err := os.OpenFile(target, os.O_CREATE|os.O_EXCL|os.O_WRONLY, 0o644)
			if err != nil {
				return fmt.Errorf("samples: unpack: %w", err)
			}
			_, cerr := io.Copy(f, tr)
			if err := f.Close(); cerr == nil {
				cerr = err
			}
			if cerr != nil {
				return fmt.Errorf("samples: unpack %s: %w", clean, cerr)
			}
		default:
			return fmt.Errorf("samples: unpack: unsupported entry type %d for %q", hdr.Typeflag, hdr.Name)
		}
	}
	return nil
}

// buildableEntryName refuses, at creation time, any name the artifact
// format or Unpack cannot carry — and says what to do about it.
//
// The canonical tar is USTAR, which is what makes identical trees produce
// identical ids. USTAR cannot encode a non-ASCII name at all, and caps a
// path component at 100 bytes. Without this check, `csx sample create`
// failed on a file named tests/café_fixture.json with archive/tar's own
// text ("Format specifies USTAR; and USTAR cannot encode Name=...") and no
// hint that renaming it is the way out — on a project whose whole subject
// is encoding and i18n, those are exactly the fixtures an author reaches
// for.
func buildableEntryName(name string) error {
	if _, err := safeEntryName(name, false); err != nil {
		return fmt.Errorf(
			"samples: %q cannot be published: an entry name may not contain "+
				"a colon, a backslash or a parent reference. Rename it", name)
	}
	for _, seg := range strings.Split(name, "/") {
		if len(seg) > ustarNameSegment {
			return fmt.Errorf(
				"samples: %q cannot be published: %q is %d bytes and the "+
					"archive format caps a path component at %d. Shorten it",
				name, seg, len(seg), ustarNameSegment)
		}
	}
	for _, r := range name {
		if r > 127 {
			return fmt.Errorf(
				"samples: %q cannot be published: the canonical archive "+
					"format is ASCII-only, which is what makes identical "+
					"trees produce identical ids. Rename the file (its "+
					"CONTENTS may be any encoding you like)", name)
		}
	}
	return nil
}

// ustarNameSegment is the USTAR limit for one path component.
const ustarNameSegment = 100

// safeEntryName validates one tar entry name and returns its cleaned
// slash-relative form.
func safeEntryName(name string, isDir bool) (string, error) {
	if name == "" ||
		strings.HasPrefix(name, "/") ||
		strings.Contains(name, `\`) ||
		strings.Contains(name, ":") ||
		strings.ContainsRune(name, 0) {
		return "", fmt.Errorf("samples: unpack: unsafe entry name %q", name)
	}
	clean := path.Clean(name)
	if clean == "." || clean == ".." || strings.HasPrefix(clean, "../") {
		return "", fmt.Errorf("samples: unpack: unsafe entry name %q", name)
	}
	segs := strings.Split(clean, "/")
	for i, seg := range segs {
		if seg == ".." {
			return "", fmt.Errorf("samples: unpack: unsafe entry name %q", name)
		}
		if (forbiddenDir(seg) || generatedDir(seg)) && (i < len(segs)-1 || isDir) {
			return "", fmt.Errorf("samples: unpack: forbidden entry %q", name)
		}
		if i == 0 && generatedRootDir(seg) && (len(segs) > 1 || isDir) {
			return "", fmt.Errorf("samples: unpack: forbidden entry %q", name)
		}
	}
	if !isDir && (isEnvFile(segs[len(segs)-1]) || forbiddenFile(segs[len(segs)-1])) {
		return "", fmt.Errorf("samples: unpack: forbidden entry %q", name)
	}
	return clean, nil
}

// within reports whether target stays inside root after cleaning.
func within(root, target string) bool {
	rel, err := filepath.Rel(root, target)
	if err != nil {
		return false
	}
	return rel != ".." && !strings.HasPrefix(rel, ".."+string(filepath.Separator))
}
