defmodule CsxEcto.TableBacked do
  use Ecto.Schema

  # The contrast for the first test. schema/2 is the same block with a table
  # name in front of it, and that name is what __schema__(:source) reports.
  # Declaring one still needs no Repo — the Repo dependency starts at the
  # first call that reads or writes the table, not at the schema.
  @primary_key false
  schema "signups" do
    field :name, :string
  end
end

defmodule CsxEcto.DefaultPk do
  use Ecto.Schema

  # What Signup would get if it did not set @primary_key false.
  embedded_schema do
    field :name, :string
  end
end

defmodule CsxEcto.SignupTest do
  use ExUnit.Case

  import Ecto.Changeset

  alias CsxEcto.DefaultPk
  alias CsxEcto.Signup
  alias CsxEcto.TableBacked

  @good %{"name" => "Ada", "email" => "ada@example.com", "age" => "36"}

  test "validation runs with ecto alone, and the schema has no table behind it" do
    # ecto_sql is a different package. Everything this file exercises comes
    # from :ecto, so the adapter layer is simply not here — no Repo to define,
    # no adapter to configure, no connection pool to start.
    assert Application.spec(:ecto, :vsn) != nil
    assert Application.spec(:ecto_sql) == nil
    refute Code.ensure_loaded?(Ecto.Adapters.SQL)

    # embedded_schema is the marker for "struct, no table", and the reflection
    # says so: a schema/2 block answers this same question with its table name.
    assert Signup.__schema__(:source) == nil
    assert TableBacked.__schema__(:source) == "signups"
    assert Signup.__schema__(:prefix) == nil
    assert Signup.__schema__(:fields) == [:name, :email, :age, :accepted_terms, :role]
    assert Signup.__schema__(:type, :age) == :integer

    assert Signup.changeset(@good).valid?
  end

  test "embedded_schema still declares an autogenerated id, which is why Signup turns it off" do
    # The default primary key is a :binary_id marked for autogeneration, and
    # autogeneration happens inside Repo.insert. With no Repo nothing ever
    # fills it in, so the field is a permanent nil that looks like an id in
    # every inspect and every JSON body until someone tries to key on it.
    assert DefaultPk.__schema__(:primary_key) == [:id]
    assert DefaultPk.__schema__(:autogenerate_id) == {:id, :id, :binary_id}

    blank = %DefaultPk{}
    assert blank.id == nil
    assert apply_changes(cast(blank, %{"name" => "Ada"}, [:name])).id == nil

    assert Signup.__schema__(:primary_key) == []
  end

  test "cast keeps the permitted fields and silently drops everything else" do
    changeset =
      Signup.changeset(%{
        "name" => "Ada",
        "email" => "ada@example.com",
        "age" => "36",
        "accepted_terms" => "true",
        "role" => "admin",
        "nickname" => "not a field at all"
      })

    # Type conversion is the visible half: strings from JSON become the
    # declared types.
    assert changeset.changes == %{
             name: "Ada",
             email: "ada@example.com",
             age: 36,
             accepted_terms: true
           }

    # The invisible half. "role" is a real field, "nickname" is not a field at
    # all, and both are treated identically: dropped, with no error and no
    # trace in the result.
    assert changeset.errors == []
    refute Map.has_key?(changeset.changes, :role)
    assert apply_changes(changeset).role == "member"

    # The permitted list is the entire defence, and it is a whitelist for this
    # reason: add :role to it by accident and the same request escalates, with
    # valid? still true and errors still empty. Nothing reports that anything
    # happened either way, so a test that only checks valid? cannot tell these
    # two changesets apart.
    escalated = cast(%Signup{}, %{"role" => "admin"}, [:name, :role])
    assert escalated.changes == %{role: "admin"}
    assert escalated.errors == []
    assert escalated.valid?

    # The dropped values are not destroyed, only ignored. changeset.params
    # holds the raw map as handed in, so an audit log or a rate limiter can
    # still see that "role" was attempted.
    assert changeset.params["role"] == "admin"
    assert changeset.params["nickname"] == "not a field at all"
  end

  test "permitting a field that does not exist raises, unlike sending one" do
    # The asymmetry is worth internalising. A typo in your own permitted list
    # is a loud ArgumentError at cast time. A key the attacker adds to the
    # request is silence. Ecto validates the list you wrote, never the params
    # you received.
    assert_raise ArgumentError, fn ->
      cast(%Signup{}, %{}, [:nickname])
    end
  end

  test "cast empties an empty string to the field default, so required fails" do
    changeset = Signup.changeset(%{"name" => "", "email" => "ada@example.com"})

    refute changeset.valid?

    # The field is absent from changes rather than present-and-empty: cast
    # compared "" against its :empty_values list and substituted the field's
    # default, which for :name is nil and therefore equal to the data, so
    # nothing was recorded as a change at all. This is why `changes[:name]`
    # reads nil in the debugger and people conclude the param never arrived.
    refute Map.has_key?(changeset.changes, :name)
    assert changeset.params["name"] == ""
    assert {"can't be blank", [validation: :required]} = changeset.errors[:name]

    # "the default", not "nil", is the actual rule, and the two only coincide
    # for a field declared without one. Over existing data an empty string
    # nils out a field with no default and silently resets a field that has
    # one — sending "" for :role does not clear it, it demotes an admin to the
    # schema default.
    assert cast(%Signup{name: "Ada"}, %{"name" => ""}, [:name]).changes == %{name: nil}
    assert cast(%Signup{role: "admin"}, %{"role" => ""}, [:role]).changes == %{role: "member"}

    # The list cast compares against is literally [""], and the comparison is
    # made after trimming, so a whitespace-only string is emptied as well.
    # Only the emptiness test trims — a value that survives it is stored
    # exactly as it was sent.
    assert Ecto.Changeset.empty_values() == [""]
    assert Signup.changeset(%{"name" => "   ", "email" => "ada@example.com"}).errors[:name]
    assert cast(%Signup{}, %{"name" => "  Ada  "}, [:name]).changes == %{name: "  Ada  "}

    # Measured, and it refutes the obvious reading of the pipeline:
    # validate_required does not run a blank check of its own. It asks
    # whether the value is nil or a member of changeset.empty_values — the
    # very list cast recorded on the changeset — so switching cast's emptying
    # off disarms validate_required at the same time, and "" is accepted as a
    # present value. The two functions look independent and are not.
    kept = cast(%Signup{}, %{"name" => ""}, [:name], empty_values: [])
    assert kept.empty_values == []
    assert kept.changes == %{name: ""}
    assert validate_required(kept, [:name]).valid?
    assert validate_required(kept, [:name]).errors == []

    # What does catch it is a validator that looks at the value, because the
    # field is now present enough to reach one.
    assert validate_length(kept, :name, min: 2).errors[:name]

    # The trimming is a separate option from the emptiness list as of 3.14.
    # Older advice to hand :empty_values a predicate now raises rather than
    # being ignored, which is the good outcome; a two-arity :trim_values
    # function is the replacement, and disabling it keeps whitespace.
    assert_raise ArgumentError, fn ->
      cast(%Signup{}, %{"name" => "  "}, [:name], empty_values: [&(&1 == "")])
    end

    untrimmed = cast(%Signup{}, %{"name" => "   "}, [:name], trim_values: fn _type, value -> value end)
    assert untrimmed.changes == %{name: "   "}
  end

  test "validate_required reads through to the struct, so a default hides it" do
    changeset = Signup.changeset(%{"email" => "ada@example.com"})

    # Presence is decided by get_field, which falls back to changeset.data
    # when there is no change. :role carries a schema default of "member", so
    # it is never missing and validate_required(:role) cannot fail whatever
    # the params contain. Requiring a field with a non-nil default is dead
    # config.
    assert field_missing?(changeset, :name)
    refute field_missing?(changeset, :role)
    assert validate_required(changeset, [:role]).errors[:role] == nil

    # Nor is the error merely being masked by the one :name already produced.
    # On a changeset with nothing else wrong, requiring :role adds nothing:
    # the check cannot fail, whatever the params were.
    good = Signup.changeset(@good)
    assert validate_required(good, [:role]).valid?
    assert validate_required(good, [:role]).errors == []
  end

  test "a type failure is a cast error, not a validation error" do
    changeset = Signup.changeset(%{"name" => "Ada", "email" => "ada@example.com", "age" => "old"})

    refute changeset.valid?

    # cast reports its own failures with validation: :cast and the target
    # type, and the field is left out of changes. Every validator after it is
    # then skipped for that field, so validate_number never sees "old" and
    # never adds a second error. Errors from cast and errors from validators
    # look alike in the errors list and are produced by completely different
    # machinery.
    assert changeset.errors[:age] == {"is invalid", [type: :integer, validation: :cast]}
    refute Map.has_key?(changeset.changes, :age)
    assert length(changeset.errors) == 1
  end

  test "valid? is a field, apply_action is the gate, apply_changes is neither" do
    ok = Signup.changeset(@good)
    assert ok.valid?
    assert ok.action == nil

    # apply_action/2 is the no-Repo equivalent of Repo.insert: it returns the
    # ok/error tuple a `with` chain expects. The action atom it takes is only a
    # label — nothing is inserted anywhere — but it must be given.
    assert {:ok, %Signup{} = applied} = apply_action(ok, :insert)
    assert applied.name == "Ada"
    assert applied.age == 36
    assert applied.role == "member"

    bad = Signup.changeset(%{"email" => "nope"})
    refute bad.valid?
    assert {:error, errored} = apply_action(bad, :insert)

    # The error branch does not hand back the changeset you passed in. It
    # stamps :action onto it, which is the flag Phoenix uses to decide whether
    # to render errors, and which makes `assert {:error, ^bad}` fail on a
    # changeset that is otherwise identical.
    assert errored.action == :insert
    assert errored.changes == bad.changes
    refute errored == bad

    # apply_changes/1 is the trap next to it. It applies the changes to the
    # struct and returns it whether or not the changeset is valid, with no
    # tuple to pattern match and nothing to ignore. Reaching for it because
    # "I just want the struct" is how invalid data gets past validation
    # entirely.
    assert %Signup{email: "nope", name: nil} = apply_changes(bad)

    assert_raise Ecto.InvalidChangesetError, fn -> apply_action!(bad, :insert) end
  end

  test "errors carry interpolation metadata, not finished sentences" do
    changeset = Signup.changeset(%{"name" => "Ada", "email" => "not-an-email", "age" => "12"})

    refute changeset.valid?

    # validate_number stores the bound in the opts and leaves a %{number}
    # marker in the message. Rendering elem(error, 0) directly is the bug:
    # the user is shown a literal "%{number}".
    assert changeset.errors[:age] ==
             {"must be greater than or equal to %{number}",
              [validation: :number, kind: :greater_than_or_equal_to, number: 18]}

    # validate_format has nothing to interpolate, so its message happens to be
    # complete. That inconsistency is what makes the bug survive review: half
    # the messages look fine without a renderer.
    assert changeset.errors[:email] == {"has invalid format", [validation: :format]}
  end

  test "traverse_errors is what turns the changeset into an API body" do
    changeset = Signup.changeset(%{"email" => "not-an-email", "age" => "12"})

    # Keys are field atoms, values are always lists — one field can collect
    # several errors — and this is the shape to build a JSON error body from.
    assert Signup.error_map(changeset) == %{
             name: ["can't be blank"],
             email: ["has invalid format"],
             age: ["must be greater than or equal to 18"]
           }

    # The values are lists because a field really can collect several errors,
    # and changeset.errors stores them as repeated keys. The keyword-list
    # lookup everyone reaches for returns the most recently added one and
    # silently discards the rest, so `changeset.errors[:email]` here reports
    # the length problem and never mentions the format problem. Grouping is
    # the job traverse_errors is doing, and it is why walking changeset.errors
    # with a keyword lookup per field loses errors.
    both = validate_length(changeset, :email, max: 3)
    assert Keyword.get_values(both.errors, :email) |> length() == 2
    assert {"should be at most %{count} character(s)", _} = both.errors[:email]

    assert Signup.error_map(both)[:email] ==
             ["should be at most 3 character(s)", "has invalid format"]
    assert Signup.error_map(Signup.changeset(@good)) == %{}
  end

  test "put_change goes around the permitted list and around the validators" do
    escalated = Signup.changeset(@good) |> put_change(:role, "admin")

    # :role is not in @permitted and put_change does not care. It writes to
    # changes directly, so it is the one call that reintroduces the mass
    # assignment problem cast/4 exists to prevent — worth grepping for in
    # review whenever the value came from a request.
    assert escalated.changes.role == "admin"
    assert escalated.valid?
    assert apply_changes(escalated).role == "admin"

    # It skips validation as thoroughly as it skips filtering. Validators are
    # ordinary functions that ran earlier in the pipeline; a change added
    # after them is never inspected, and the changeset still reports valid?.
    late = Signup.changeset(@good) |> put_change(:age, 12)
    assert late.changes.age == 12
    assert late.valid?
    assert late.errors == []

    # Running the same validator again does catch it, which is the fix when a
    # put_change has to stay: the pipeline order is the semantics.
    assert validate_number(late, :age, greater_than_or_equal_to: 18).errors[:age]

    # And put_change is a no-op when the value already equals the one on the
    # struct, because a changeset records differences rather than assignments.
    # Forcing the write is what force_change/3 is for.
    unchanged = put_change(Signup.changeset(@good), :role, "member")
    refute Map.has_key?(unchanged.changes, :role)
    assert force_change(Signup.changeset(@good), :role, "member").changes.role == "member"
  end
end
